executable            = runPOWHEG.sh
arguments             = $(ClusterID) $(ProcId)

should_transfer_files = YES
transfer_input_files = powheg.input, RunPythia8.C
when_to_transfer_output = ON_EXIT

output                = /afs/cern.ch/user/h/hapark/log/output/std.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/h/hapark/log/error/std.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/h/hapark/log/std.$(ClusterId).log

+JobFlavour = "nextweek"
queue 200
